-- MySQL Script generated by MySQL Workbench
-- Fri Nov  2 20:58:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema busalot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema busalot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `busalot` DEFAULT CHARACTER SET latin1 ;
USE `busalot` ;

-- -----------------------------------------------------
-- Table `busalot`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `busalot`.`Company` (
  `company_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `telephone` VARCHAR(14) NULL,
  `website` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `city` VARCHAR(100) NULL,
  PRIMARY KEY (`company_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `busalot`.`Bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `busalot`.`Bus` (
  `bus_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `trailer_option` VARCHAR(45) NULL,
  `disability` TINYINT(1) NULL,
  `rating` INT(1) NULL,
  `size` INT(3) NULL,
  `company_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`bus_ID`),
  INDEX `Companyid_idx` (`company_ID` ASC) VISIBLE,
  CONSTRAINT `Companyid`
    FOREIGN KEY (`company_ID`)
    REFERENCES `busalot`.`Company` (`company_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `busalot`.`Routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `busalot`.`Routes` (
  `route_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `price` VARCHAR(10) NULL,
  `journey_time` VARCHAR(45) NULL,
  `start_location` VARCHAR(255) NULL,
  `end_location` VARCHAR(255) NULL,
  `bus_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`route_ID`),
  INDEX `Busid1_idx` (`bus_ID` ASC) VISIBLE,
  CONSTRAINT `Busid1`
    FOREIGN KEY (`bus_ID`)
    REFERENCES `busalot`.`Bus` (`bus_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `busalot`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `busalot`.`Users` (
  `user_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` TEXT NULL,
  `company_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_ID`),
  INDEX `Companyid1_idx` (`company_ID` ASC) VISIBLE,
  CONSTRAINT `Companyid1`
    FOREIGN KEY (`company_ID`)
    REFERENCES `busalot`.`Company` (`company_ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
